docs/gatsby-config.js, docs/gatsby-node.js, docs/src/components/Layout/index.js, docs/src/components/Layout/style.scss, docs/src/components/LinkedHeading/index.js, docs/src/components/LinkedHeading/style.scss, docs/src/components/Playground/index.js, docs/src/components/Playground/style.scss, docs/src/components/SideNav/index.js, docs/src/components/SideNav/style.scss, docs/src/components/Toc/index.js, docs/src/components/Toc/style.scss, docs/src/components/TopBar/index.js, docs/src/components/TopBar/style.scss, docs/src/pages/components/badge.mdx, docs/src/pages/get-started/introduction.mdx, docs/src/pages/layout/grid.mdx
=> feat: Add introduction docs

docs/content/components/tooltip.mdx, docs/src/components/Playground/index.js, docs/src/components/Playground/style.scss, package.json, src/interface.tsx, src/lib/Tooltip/index.tsx, src/lib/Tooltip/style.scss, src/lib/index.tsx, yarn.lock
=> feat: Tooltip component and doc

.travis.yml, docs/content/components/badge.mdx, package.json, src/components/Badge/index.test.tsx, src/setupTests.ts
```
-------------------------|----------|----------|----------|----------|-------------------|
File                     |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-------------------------|----------|----------|----------|----------|-------------------|
All files                |     5.47 |     7.37 |     5.26 |     5.76 |                   |
src                     |        0 |        0 |        0 |        0 |                   |
index.ts               |        0 |        0 |        0 |        0 |                   |
interface.tsx          |        0 |        0 |        0 |        0 |                   |
src/components          |        0 |        0 |        0 |        0 |                   |
index.tsx              |        0 |        0 |        0 |        0 | …
```
=> feat: Add test coverage

.storybook/webpack.config.js, package.json, src/global.d.ts, webpack.config.js
支持 css module，只有以 module.scss 结尾的文件才会启用
=> feat: Support css module.

docs/content/components/well.mdx
=> fix: Rename well component.

src/components/RangePicker/style.scss
http://issue.xsky.com/browse/WIZARD-5127
=> fix rangePicker comp abnormal line break problem.

src/utils/bulk.ts
http://issue.xsky.com/browse/WIZARD-5114
https://github.com/xsky-fe/wizard-ui/issues/101
=> fix: associate local storage to get correct current locale.

src/components/UsageBar/style.scss
Limit UsageBar component min-width
=> fix: [XEUS-1421] Limit UsageBar component min-width

src/components/Tabs/index.tsx, src/components/Tabs/style.scss
tabs 在项目中没有继承高度
- 解决方法
修改样式
- 解决效果
=> Change tab height to inherit

src/components/Tabs/style.scss
Signed-off-by: zghzzj <2627191377@qq.com>
- 优化
移除tabs组件宽度限制。
- 结果
=> remove tab limit width

docs/content/components/usage-bar.mdx, src/components/UsageBar/style.scss
- 移除UsageBar 中 min-width 属性
- 相关的issue：
http://issue.xsky.com/browse/XEUS-1421  
以前添加min-width解决这个issue，现在此issue以后再优化
=> fix: UsageBar Remove min-width.

src/components/UsageBar/index.tsx, src/components/UsageBar/style.scss, src/interface.tsx, src/utils/bulk.ts, src/utils/xbytes.ts, stories/UsageBar.stories.tsx
http://localhost:6006/?path=/story/data-show-usagebar--series
UsageBar 支持 SERIES 数据集模式，适用于多段 ProgressBar 场景；
=> improve: UsageBar support series and lenged.

src/components/UsageBar/index.tsx, src/components/UsageBar/style.scss, stories/UsageBar.stories.tsx
=> improve: UsageBar support default style.

docs/package.json, package.json, src/components/DatePicker/style.scss, stories/Modal.stories.tsx, yarn.lock
=> refactor: Modal picker

src/components/DropdownButton/index.tsx
Signed-off-by: genghai <genghai@xsky.com>
解决点击menuItem后组件没有合起问题
- issue
http://issue.xsky.com/browse/XEUS-1765
=> Add menuItem click to control dropdownbutton open.

src/components/DropdownButton/index.tsx, src/interface.tsx, stories/InputGroup.stories.tsx
Signed-off-by: genghai <genghai@xsky.com>
- 修改dropdownbutton 点击盒子收起 https://github.com/xsky-fe/wizard-ui/pull/144 引入的问题，menuItem中 onSelect 被占用问题。
- sotrybook 增加调试用例
=> fix dropdownbutton.

src/components/UsageBar/index.test.tsx, src/components/UsageBar/index.tsx
Added judgment condition boundary processing
=> fix: UsageBar color display

src/components/RangePicker/style.scss
修改前：
修改后：
https://issue.xsky.com/browse/XSOS-340
=> fix: Optimize RangePicker style.

src/components/UsageBar/index.tsx
Signed-off-by: xiaojing <xiaojing@xsky.com>
关联issue[需要设置进度条最小展示](https://issue.xsky.com/browse/XGFS-2771)
=> fix:[usageBar]add show limit for usageBar

src/components/UsageBar/style.scss, src/style/variables.scss
Signed-off-by: qianwen@xsky.com <qianwen@xsky.com>
更新 usagebar 组价中的样式，新增 chart1 ~ chart6 颜色循环样式。
=> feat: Update usagebar component style.

src/components/DropdownButton/index.tsx
Signed-off-by: xiaojing <xiaojing@xsky.com>
解决menu 控制台报错：
=> fix: fix menu props error

src/components/DropdownButton/index.tsx
Signed-off-by: zhanghuan <zhang.huan@xsky.com>
修复dropdownButton子菜单异常重绘问题，需配置 xsky-wixard 改动传入的menu，保证值不会每次都改变。
测试截图：
=> fix: update DropdownButton item key

package.json
Signed-off-by: linsheng <linsheng1@xsky.com>
=> fix: remove engines limit in package.json

docs/src/Layout/bootstrap-custom.scss, docs/src/Layout/style.scss, docs/src/Layout/variables.scss, docs/src/components/Beta/style.scss, docs/src/components/Header/style.scss, docs/src/components/Icon/style.scss, docs/src/components/PropTable/style.scss, docs/src/components/Toc/style.scss, docs/src/components/TopBar/style.scss, src/components/Badge/style.scss, src/components/DatePicker/style.scss, src/components/Loader/style.scss, src/components/Navigation/style.scss, src/components/Notification/style.scss, src/components/Popover/style.scss, src/components/RangePicker/style.scss, src/components/SubMenu/style.scss, src/components/Tabs/style.scss, src/components/TimePicker/style.scss, src/components/Tooltip/style.scss, src/components/UsageBar/style.scss, src/components/VirtualSelectBox/style.scss, src/style/bootstrap-custom.scss, src/style/variables.scss, stories/Alert.stories.tsx
同步修改
https://github.xsky.com/front-end/xsky-wizard/pull/5636
https://github.xsky.com/front-end/xsky-wizard/pull/5655
=> feat: font-family and font-size update

.storybook/config.ts, src/style/bootstrap-custom.scss, src/style/index.scss
旧新的变量大多数已经不适用，重新引入 5版本的变量文件。
目前的变量文件：
- 修改了根字体大小，颜色
- 旧文件涉及修改的颜色变量移植到新的变量文件了
- border-radius 修改了
剩下的需要各个业务场景过一遍
变量文件地址
=> fix: change variables

src/components/Notification/Notification.tsx, src/components/Notification/style.scss
=> refactor: modify Notification component

src/components/Dropdown/index.tsx, src/components/Dropdown/style.scss, src/style/bootstrap-custom.scss
=> refactor: upgrade dropdown

src/components/SubMenu/index.tsx, src/components/SubMenu/style.scss
需要等 https://github.com/xsky-fe/wizard-ui/pull/223 合入后
升级前：
升级后：
=> refactor: upgrade submenu

src/components/Modal/style.scss
=> fix: remove static modal bounce

src/components/Button/index.tsx, src/components/Button/style.scss, src/interface.tsx, src/style/bootstrap-custom.scss, stories/Button.stories.tsx
=> refactor: button

src/components/Panel/index.tsx, src/style/bootstrap-custom.scss
=> refactor: panel

src/components/Tabs/index.tsx, src/components/Tabs/style.scss, src/style/bootstrap-custom.scss
=> refactor: tabs

src/components/Popover/index.tsx, src/components/Popover/style.scss, src/interface.tsx, src/style/bootstrap-custom.scss, stories/Popover.stories.tsx
=> refactor: popover

src/interface.tsx, stories/Tree.stories.tsx
=> refactor: add tree storybook desc

stories/Checkbox.stories.tsx, stories/InputGroup.stories.tsx, stories/Radio.stories.tsx
=> refactor: add checkbox and radio storybook

src/components/Tooltip/index.tsx, src/interface.tsx, stories/Button.stories.tsx, stories/Tooltip.stories.tsx
=> refactor: adapter the tooltip comp

src/components/VirtualSelectBox/index.tsx, src/components/VirtualSelectBox/style.scss
VirtualSelectBox 修改点
- 移除清除按钮
- 下拉组件替换成DropButton组件
- Panel替换成Card组件
升级前：
升级后：
=> refactor: adjust to virtualSelectBox

stories/Pagination.stories.tsx
=> add pagination storybook

src/components/Panel/index.scss, stories/Panel.stories.tsx
=> refactor: panelGroup

stories/Collapse.stories.tsx, stories/SplitButton.stories.tsx, stories/ToggleButtonGroup.stories.tsx
=> feat: add collapse splitButton toggleButton storybook

src/components/DropdownButton/index.tsx, src/components/Navigation/index.tsx, src/components/Navigation/style.scss, src/components/Panel/index.scss, src/components/Panel/index.tsx, src/interface.tsx, src/style/bootstrap-custom.scss, stories/Navigation.stories.tsx, stories/Panel.stories.tsx
=> refactor: navigation

src/components/Panel/index.scss, src/components/Panel/index.tsx, src/interface.tsx
=> fix: modify panel style

src/components/Navigation/index.tsx, src/components/Panel/index.tsx, src/components/Tabs/style.scss, src/components/VirtualSelectBox/style.scss, src/interface.tsx
=> fix: panel

src/components/DropdownButton/style.scss, src/components/UsageBar/index.tsx
=> fix: revert col

src/components/Navigation/style.scss, stories/Alert.stories.tsx, stories/Badge.stories.tsx, stories/Breadcrumb.stories.tsx, stories/Button.stories.tsx, stories/Collapse.stories.tsx, stories/Dropdown.stories.tsx, stories/DropdownButton.stories.tsx, stories/InputDropdown.stories.tsx, stories/InputGroup.stories.tsx, stories/Modal.stories.tsx, stories/Nav.stories.tsx, stories/Navigation.stories.tsx, stories/Pagination.stories.tsx, stories/Panel.stories.tsx, stories/Popover.stories.tsx, stories/ProgressBar.stories.tsx, stories/SplitButton.stories.tsx, stories/Steps.stories.tsx, stories/SubMenu.stories.tsx, stories/Switch.stories.tsx, stories/Tabs.stories.tsx, stories/TimePicker.stories.tsx, stories/ToggleButtonGroup.stories.tsx, stories/Tooltip.stories.tsx
=> fix: add some storybook

src/components/DropdownButton/index.tsx, stories/DropdownButton.stories.tsx
dropDownBtn tooltip 设置默认值为 item.title
=> fix: dropDownBtn tooltip label default

src/components/Switch/index.tsx, src/components/Switch/style.scss, src/interface.tsx, src/style/variables.scss, stories/Switch.stories.tsx
[Switch 设计规范](https://www.figma.com/file/wxFB2rM9uT7E79V2o5A5hU/SDS-6.0-%E8%AE%BE%E8%AE%A1%E8%A7%84%E8%8C%83?type=design&node-id=4259-34425&t=WgpTMglYzluKFeJR-0)
[关联 wizard 的 Pr](https://github.xsky.com/front-end/xsky-wizard/pull/6044)
新增参数
- loading?: boolean;  状态
- colorIndex?: 1 -11颜色序列
- size?: lg | sm
开关新增五个状态颜色
=> refactor: switch change

package.json, src/components/UsageBar/index.tsx, src/interface.tsx, stories/UsageBar.stories.tsx, stories/docs/UsageBar.mdx
- usagebar 增加 `bsStyle` 属性，支持自定义bar颜色
- usagebar 增加 `handleCustomFooter` 属性 ，支持自定义底部展示
- 数字与单位间增加空格 https://xskydata.feishu.cn/wiki/wikcnLHXwvNmQ11kSQyiywqJJ0F
- 修复单词拼写错误问题
=> feat:usagebar

src/components/Button/index.tsx
=> fix: button warning

docs/src/Layout/variables.scss, src/components/Badge/style.scss, src/components/Button/style.scss, src/components/DatePicker/style.scss, src/components/Modal/style.scss, src/components/Popover/index.tsx, src/components/Popover/style.scss, src/components/RangePicker/style.scss, src/components/TimePicker/style.scss, src/components/Tree/style.scss, src/style/bootstrap-custom.scss, src/style/bootstrap.scss, src/style/variables.scss, stories/Popover.stories.tsx, stories/docs/Tree.mdx
https://xskydata.feishu.cn/wiki/KY0Iw3D0UiwIWYkffeQcnosIn2c
=> fix: ui style

src/components/VirtualList/index.tsx, src/interface.tsx
[【6.3.000.0】【特性测试】【操作日志】构造ES故障，带条件查询操作日志，显示多一条直线](https://issue.xsky.com/browse/XSOS-6281)
修改前：
修改后：
=> fix: fix vlist error try to fetch data

src/components/Modal/index.tsx
=> feat: Modal Component add onShow fun props

src/components/FormCheck/index.tsx
新增 formcheck的 input 和 label组件
原因：后续需要拆开单选框的 按钮和 标签
=> fix: add formcheck input and label

src/components/DropdownButton/style.scss, src/components/Loader/style.scss, src/components/SubMenu/style.scss
- 重构：调整 Loader 组件的色值，大小等样式；
- 重构：调整 DropdownButton，Dropdown 组件样式；
=> refactor: modify Loader and Dropdown Components style

src/components/Tooltip/style.scss
=> fix: modify tooltip

src/style/bootstrap-custom.scss, src/style/variables.scss
=> refactor: adjust popover style

src/components/Button/style.scss, src/style/variables.scss
- 新增box shadow
- info button样式调整
=> refactor: adjust button style

src/components/UsageBar/style.scss
=> style: modify profress default color

src/components/DatePicker/style.scss, src/components/Modal/index.tsx
- 问题：修复时间选择器的乱码展示
- 功能：Modal组件新增onShow方法属性
=> fix: [XSOS-6604][XSOS-6522] fix datepicker display error & add onShow Props to Modal Component

src/components/Badge/index.tsx, src/components/Badge/style.scss, src/components/Button/style.scss, src/components/Dropdown/style.scss, src/components/DropdownButton/style.scss, src/components/Loader/style.scss, src/components/Steps/index.tsx, src/components/SubMenu/style.scss, src/components/Tooltip/index.tsx, src/components/Tooltip/style.scss, src/interface.tsx, src/style/bootstrap-custom.scss, src/style/variables.scss, stories/Tooltip.stories.tsx
- Dropdown https://github.com/xsky-fe/wizard-ui/pull/300
- Loader https://github.com/xsky-fe/wizard-ui/pull/300
- Badge https://github.com/xsky-fe/wizard-ui/pull/295
- Tooltips https://github.com/xsky-fe/wizard-ui/pull/294
- Popover https://github.com/xsky-fe/wizard-ui/pull/299
- Button https://github.com/xsky-fe/wizard-ui/pull/303
=> refactor: modify SDS component style to adjust SDDC component style

src/components/Steps/index.tsx
=> fix: fix step component error

src/components/Button/style.scss, stories/Button.stories.tsx
=> refactor: add button text variant

src/components/Badge/style.scss
=> fix badge style
