xsky-fe/wizard-ui

docs/content/components/breadcrumb.mdx
feat: Breadcrumb.
update breadcrumb doc.
=> feat: Breadcrumb.

docs/content/layout/font.mdx, docs/src/Layout/bootstrap-custom.scss, docs/src/Layout/variables.scss, src/style/bootstrap-custom.scss, src/style/variables.scss
=>  Feat: Add Font specification

docs/gatsby-config.js, docs/package.json, docs/src/components/HeaderSearch.js, docs/src/components/Search/index.js, docs/src/components/Search/style.scss, docs/src/components/TopBar/index.js, docs/yarn.lock
=> feat: Docs support search

src/utils/bulk.ts
兼容异常的 LOCALE 变量，不为 'en' 时默认为 'zh'
=> improve: compatible with abnormal LOCALE value.

src/components/UsageBar/index.tsx
http://issue.xsky.com/browse/WIZARD-5192?filter=-1
问题原因：calcPercent 中先将 percent * 100 了，所以小于 0.01% 的判断应该为 percent < 0.01；
所以之前 0.0001～0.000001 之间的没法正常显示为 0.01%
=> fix: abnormal percentage display.

docs/content/components/tab.mdx, src/components/Tabs/index.tsx
问题：tabs组件内容的选择没有根据页面路由决定 （页面刷新，路由是“生命周期”，而tabs渲染后内容指定是第一个）
修改：通过传入的activekey，渲染tabs选中的内容。
=> fix/tabs: Tabs-body should changes width route

src/components/Tabs/index.tsx, src/components/Tabs/style.scss
Signed-off-by: zghzzj <2627191377@qq.com>
##优化：限制tab标题的宽度
以中文字体6字为标准 max-width=120px
##优化结果：
可以按照设计方案使用，s鼠标移动上去，会显示全部标题
##测试结果： 
给 NavItem 添加 title属性，导致渲染rander tabs 的断言测试失败。
=> Limit tab max-width

docs/content/components/usage-bar.mdx, src/components/UsageBar/index.tsx, src/interface.tsx, src/utils/bulk.ts, src/utils/xbytes.ts
* 容量的 xbyte 函数增加格式化参数
* decimal 代表10进制， binary 代表二进制
* 由于xbyte 函数之前的使用其实都是 binary， 所以为了兼容之前的将原先的保留继续使用， 而后的需求如果需要这块则自定义格式
* 原先有多处使用 xbyte，都是错误使用，之后再改，先兼容
=> feat: Add format usage bar.

src/components/Tooltip/style.scss
- 线上测试表中或者表单中Tooptip的icon图标大，而本地测试正常
- 原因 样式优先级问题
- 修改，调试线上版本10.252.3.61:8056 方式解决bug
- 修改前
- 修改后
=> fix: [XEUS-1099] Change Tooltip sass

docs/content/components/usage-bar.mdx, src/components/UsageBar/index.tsx
Signed-off-by: zghzzj <2627191377@qq.com>
- bug 原因
项目中
docs测试
```
...
...
...
<UsageBar isByte max={0} />
<UsageBar isBulk max={0} /> 
```
- 解决结果
issue
http://issue.xsky.com/browse/XEUS-1130
=> fix: [XEUS-1130] Fix UsageBarLimit value.

src/components/Tabs/index.tsx
http://issue.xsky.com/browse/WIZARD-5318
=> fix: Tabs only show string title.

src/components/Tabs/style.scss
Signed-off-by: genghai <genghai@xsky.com>
#移除“更多” 盒子宽度限制
解决国际化英文单词过长换行问题
- 修改前
- 修改后
=> fix remove tab max-width.

src/components/UsageBar/style.scss
移除 UsageBar 中 PercentStack__tooltip-item 相关的样式，UsageBar tooltip 样式在 wizard UsageWrapper 组件中实现
=> improve: Remove styles not belong to UsageBar.

src/components/DatePicker/index.tsx
https://github.com/react-component/calendar/commit/46fc91eaffece4486cc60d25821f3745a444878f?diff=split
rc-calendar 版本改动，修复modal里日期选择框打开就闪退的问题
=> fix: Close calendar picker on blur

package.json, src/components/Modal/index.test.tsx, src/components/Modal/index.tsx, src/components/Modal/style.scss, src/interface.tsx, src/style/bootstrap-custom.scss, stories/Modal.stories.tsx, yarn.lock
在Modal头部增加一个区域供modal组件拖拽判定，保证modal的内容不在屏幕外。
增加2个props属性：
1. draggable：开启拖拽功能（默认为true）。
2. preventDragByTitle：在title区域禁掉拖拽功能。
拖拽区域限定截图：
=> Feat: Add drag-and-drop functionality in modal

src/components/Modal/style.scss
Signed-off-by: zhanghuan <zhang.huan@xsky.com>
当关闭 icon 的样式 opacity 被覆盖为1时，无法点击。
解决方式：通过 position: 'relative' 设置 icon 的层级
复现截图：
=> fix: Modal close icon can not click

src/components/Modal/index.tsx, src/components/Modal/style.scss
Signed-off-by: zhanghuan <zhang.huan@xsky.com>
思路：改变拖动的对象为滚动条内部的元素。目前版本 react- bootstrap 不支持把用 React 组件嵌套 Modal 的内容部分，创造一个新的dom作为拖动的容器，设置class为 ‘.modal-content’ 以保持样式。为避免2份样式再覆盖原本的 .modal-content 样式。
自测截图：
=> fix: Draggable Modal moves the browser scroll bar

src/components/UsageBar/index.tsx
Signed-off-by: qianwen@xsky.com <qianwen@xsky.com>
关联问题单：
- [存储平台创建/修改界面 ，存储池有效容量对应的进度条，已用容量很小的时候，进度条视觉效果不明显](https://issue.xsky.com/browse/XEOS-6821)
根据原有pr：
- https://github.com/xsky-fe/wizard-ui/pull/156
- 进行优化，删除百分比0.00005的限制
=> fix: [usageBar] update usage-bar component minWidth style

src/components/UsageBar/index.tsx, stories/UsageBar.stories.tsx
- storybook
- 真实环境 http://10.16.13.216:8056/
相关issue: [配置桶容量配额或者对象配额为0，桶内容量或者对象数超过配额后，界面未更新为对应的颜色](https://issue.xsky.com/browse/XEOS-5560)
=> fix: update UsageBar to show percent when max is 0 and zero max shown

src/components/UsageBar/index.tsx, src/components/UsageBar/style.scss, src/interface.tsx, stories/UsageBar.stories.tsx
[桶压缩FR](https://issue.xsky.com/browse/XEOS-8456) 需要 UsageBar 在数值后显示显示额外信息
storybook:
wizard里效果:
=> feat: enable extra info shown in UsageBar footer

docs/gatsby-node.js
=> fix: fix the problem that some pages cannot be found

src/components/Modal/index.test.tsx, src/components/Modal/index.tsx, src/components/Modal/style.scss, src/interface.tsx, src/style/bootstrap-custom.scss
升级前：
升级后：
属性变更：
- 新增 centered ，可以使得 Modal 垂直居中
样式变更：
- modal 的圆角之前规范设置遗漏了，这次改为 4px
- xlarge 样式被迁移到 wizard-ui里，
=> refactor: upgrade modal

docs/src/components/Search/index.js, stories/InputGroup.stories.tsx
v5 不支持 <InputGroup.Addon> 用法，改为以下用法
=> modify input group component

src/components/Steps/index.tsx, src/components/Steps/style.scss, stories/Steps.stories.tsx
旧版 steps 最外层使用了 well 组件包裹，现已弃用该组件，将项目中步骤条相关样式搬过来。
=> refactor: steps style

src/components/Dropdown/index.test.tsx, src/components/DropdownButton/index.test.tsx, src/components/DropdownButton/index.tsx, src/components/DropdownButton/style.scss, src/interface.tsx, src/style/bootstrap-custom.scss, stories/DropdownButton.stories.tsx, stories/InputGroup.stories.tsx
升级前：
升级后：
变更：
1. bsize  -> size
2. bsStyle -> variant
3. componentClass -> as
4. dropup -> drop，支持 string 去指定弹出方向
5. open  -> show
6. pullRight -> align，支持 string 去指定对齐方向
=> refactor: upgrade dropdownButton

src/components/Dropdown/style.scss
[【UI验收】全局资源项点击操作，下拉小三角icon方向没有变化](https://issue.xsky.com/browse/XSOS-4954?filter=-1)
=> fix: [XSOS-4954] change dropdown direction

src/components/Dropdown/style.scss, src/components/DropdownButton/style.scss, src/components/Modal/style.scss, src/components/Popover/style.scss, src/components/RangePicker/style.scss, src/components/Tooltip/style.scss, src/style/bootstrap-custom.scss, src/style/variables.scss
[阴影设计规范](https://www.figma.com/file/wxFB2rM9uT7E79V2o5A5hU/SDS-6.0-%E8%AE%BE%E8%AE%A1%E8%A7%84%E8%8C%83?type=design&node-id=3737-32903&t=KJIefWqIDjn0ZZZi-0)
涉及组件：
- popver
- tooltip
- dropdown
- modal
- rangerpicker,datapicker
- panel （后续开发卡片的时候，区分底层卡片和内嵌卡片的 阴影效果）
变化前：
变化后：
关联pr: https://github.xsky.com/front-end/xsky-wizard/pull/5926
=> fix: change box shadow

src/components/Panel/index.scss, src/components/Panel/index.tsx, src/components/Tabs/index.tsx, src/components/UsageBar/index.tsx, src/interface.tsx
[figma 卡片规范](https://www.figma.com/file/wxFB2rM9uT7E79V2o5A5hU/SDS-6.0-%E8%AE%BE%E8%AE%A1%E8%A7%84%E8%8C%83?type=design&node-id=2045-27202&t=qWGnXePwNrOXrRmN-0)
卡片新增内嵌和内边距尺寸属性，不同的样式
- 嵌套的卡片没有阴影，
- 详情页的卡片使用 sm大小；拓扑的卡片使用 xs 大小
=> fix: change panel style

src/components/Tooltip/style.scss
=> fix: tooltip contrast arrow color

src/components/Button/index.test.tsx, src/components/Button/index.tsx, src/components/DropdownButton/index.tsx, src/interface.tsx, stories/Button.stories.tsx, stories/DropdownButton.stories.tsx
button 传入的 tooltip 支持 false ,用来支持下面的写法
```js
<Button
tooltip={ boolean && {
children: 'xx'
}}
>
xx
</Button>
```
Button & DropdownButton 的 tooltip 拼写错误修复
realated: https://github.xsky.com/front-end/xsky-wizard/pull/6264
https://xskydata.feishu.cn/wiki/CrSowghZoiAIuBkgezjcqf8lnme
=> feat: add false type in button tooltip

src/components/Switch/index.tsx
[【组件升级】创建存储桶页面，开启压缩后，追加写的swich组件disable状态时预期透明度为0.3.](https://issue.xsky.com/browse/XEOS-9576)
=> fix: [XEOS-9576] change switch disabled opacity

src/components/Button/style.scss
问题：
wizard 全局问题，disabled button 的 tooltip 一直悬浮，不会消失
storybook 上也有：
被 button disabled 的属性影响了
=> fix: button tooltip bug

src/components/Button/style.scss, src/components/DatePicker/style.scss, src/components/Popover/index.tsx, src/components/RangePicker/style.scss, src/components/TimePicker/style.scss
https://xskydata.feishu.cn/wiki/KY0Iw3D0UiwIWYkffeQcnosIn2c
剩余问题
=> fix: ui problems

src/components/Badge/style.scss, src/components/UsageBar/style.scss, src/style/variables.scss
[【存储池】存储池详情中图例圆点大小不统一&圆点和标签预期上下居中对齐](https://issue.xsky.com/browse/XEOS-9893)
=> fix: dot-size

src/components/VirtualList/index.tsx, src/components/VirtualList/style.scss
- [缩放屏幕恢复后，资源详情页下拉空包页面居多无法恢复](https://issue.xsky.com/browse/XSOS-6016?filter=-1&jql=assignee%20in%20(currentUser())%20order%20by%20updated%20DESC)
=> fix: [XSOS-6016] fix VirtualList resize height error

src/components/Tabs/style.scss
- [【管理面】分辨率1280px时，站点详情更多下拉和列表tab层级问题。](https://issue.xsky.com/browse/XEOS-9999?filter=-1&jql=project%20in%20(XSOS%2C%20XEOS)%20AND%20assignee%20in%20(currentUser())%20order%20by%20updated%20DESC)
修复前：
修复后：
=> fix: [XEOS-9999] fix tag z-index error

src/components/DatePicker/style.scss, src/components/Tabs/style.scss
- [【6.3.000.0】【特性测试】【操作日志】操作日志 按时间过滤组件中存在乱码](https://issue.xsky.com/browse/XSOS-6275?filter=-1&jql=project%20in%20(XSOS%2C%20XEOS)%20AND%20assignee%20in%20(currentUser())%20ORDER%20BY%20summary%20ASC%2C%20updated%20DESC)
修复前：
修复后：
-[【管理面】分辨率1280px时，站点详情更多下拉和列表tab层级问题。](https://issue.xsky.com/browse/XEOS-9999?filter=-1&jql=project%20in%20(XSOS%2C%20XEOS)%20AND%20assignee%20in%20(currentUser())%20ORDER%20BY%20summary%20ASC%2C%20updated%20DESC)
修复前：
修复后：
=> fix: [XSOS-6275][XEOS-9999] fix datepicker code format error

src/components/Tooltip/index.tsx, src/components/Tooltip/style.scss, src/interface.tsx
- [【组件】全局固定tooltips三角居中后，平台概览靠右侧小i的tooltips偏移显示问题。](https://issue.xsky.com/browse/XSOS-6398?filter=-1&jql=project%20in%20(XSOS%2C%20XEOS)%20AND%20assignee%20in%20(currentUser())%20order%20by%20updated%20DESC)
=> fix: [XSOS-6398] fix tooltips center error

src/components/Alert/style.scss
[【6.3.1】【对象归档池】创建所有存储池，创建及操作显示池名称的页面，名称显示超长，优化显示](https://issue.xsky.com/browse/XSOS-6742)
=> fix: alert text overflow wrap
